name: Try Building LaTeX document

on:
  pull_request:
    branches: 
    - master
  push:
    branches-ignore:
    - master

jobs:
  try_build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
