name: Try Building LaTeX document

on:
  pull_request:
    branches: 
    - master
  push:
    branches-ignore:
    - master

jobs:
  try_build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      
      - name: Check if main.tex exists
        id: main_check
        uses: andstor/file-existence-action@v3
        with:
          files: "main.tex"
        
      - name: Compile LaTeX document
        if: steps.main_check.outputs.files_exists == 'true'
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
